Server:
  port: 9193

datasource:
  url: jdbc:h2:mem:testdb

spring:
  h2:
    console:
      enabled: true
  application:
    name: FIRSTMICROSERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


file:
  storage:
    location: /fileStorage